[build]
  # The command to run to build your site
  command = "npm run build"

  # The directory that contains the deploy-ready HTML files and assets
  publish = "dist"

# Single Page Application (SPA) redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
